# This defines the pingfederate deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
  labels:
    app: pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfederate
  template:
    metadata:
      name: pingfederate
      labels:
        app: pingfederate
    spec:
      containers:
      - name: pingfederate
        image: pingidentity/pingfederate:9.3.0-edge
        ports:
        - containerPort: 9999
          name: pf-console
        envFrom:
          - configMapRef:
              name: pingfederate-environment-variables