kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
#- ../common
- deployment.yaml
- service.yaml
- ingress.yaml

#namePrefix: pingfederate-

commonLabels:
  role: pingfederate

configMapGenerator:
- name: pingfederate-environment-variables
  env: env_vars