
version: "3.1"
services:
  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingfederateconsole:9999 -t 400 -- entrypoint.sh start-server
    environment:
      - CLUSTER_NAME=test
      - DISCOVERY_S3_LOCATION=gm-docker-swarm-cluster
      - DISCOVERY_S3_ACCESS_KEY=AKIAYLKNAJBJDJUUQB45
      - DISCOVERY_S3_SECRET_KEY=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
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      # - PA_HOSTNAME={f.q.d.n} # only if using variablized import.
      # - PD_HOSTNAME={f.q.d.n} # only if using variablized import.
      # - PF_HOSTNAME={f.q.d.n} # only if using variablized import.
      - SERVER_PROFILE_URL=https://github.com/ping-devops-program/ping-poc-base
      - SERVER_PROFILE_PATH=server-profiles/clustered-pf/pingfederate
    env_file:
      - ~/.pingidentity/devops
    # volumes:
      # - ${HOME}/projects/devops/volumes/pingfederate:/opt/out
      # - ${HOME}/projects/ping-poc-base/server-profiles/clustered-pf/pingfederate:/opt/in
    ports:
      - 9031:9031
    networks:
      - pingnet-dmz
      - pingnet-internal
  pingfederateconsole:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    # command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - CLUSTER_NAME=test
      - DISCOVERY_S3_LOCATION=gm-docker-swarm-cluster
      - DISCOVERY_S3_ACCESS_KEY=AKIAYLKNAJBJDJUUQB45
      - DISCOVERY_S3_SECRET_KEY=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
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      # - PA_HOSTNAME={f.q.d.n} # only if using variablized import.
      # - PD_HOSTNAME={f.q.d.n} # only if using variablized import.
      # - PF_HOSTNAME={f.q.d.n} # only if using variablized import.
      - SERVER_PROFILE_URL=https://github.com/ping-devops-program/ping-poc-base
      - SERVER_PROFILE_PATH=server-profiles/clustered-pf/pingfederate
    env_file:
      - ~/.pingidentity/devops
    # volumes:
      # - ${HOME}/projects/devops/volumes/pingfederate:/opt/out
      # - ${HOME}/projects/ping-poc-base/server-profiles/clustered-pf/pingfederate:/opt/in
    ports:
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
networks:
    pingnet-internal:
    pingnet-dmz: