# FIXME: This is just a test cert that's meant to show how secrets can be
# created with certs and used by the nginx ingress controller. When we have
# CA-certs, put them here.
# FIXME: The private key is in the clear!!!

# NOTES:
#
# To generate a CSR (to be submitted to a CA) for ping.aws.com, follow these steps:
#
# 1. Generate the RSA private key:
#      openssl genrsa -out ping-aws.rsa 4096
#
# 2. Create a CSR to submit to CA:
#      openssl req -new -key ping-aws.rsa -out ping-aws.csr \
#        -reqexts SAN -extensions SAN -subj '/CN=ping-aws.com' \
#        -config <(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:*.ping-aws.com")
#
# 3. Obtain the CA-signed certificate and put it in ping-aws.crt
#
# ---
#
# For test purposes, create a key and a self-signed certificate in one step:
#
# 1. For test purposes, create a key and a self-signed certificate in one step:
#      openssl req -x509 -nodes -newkey rsa:2048 -days 3650 -sha256 \
#        -keyout ping-aws.key -out ping-aws.crt -subj '/CN=ping-aws.com' \
#        -reqexts SAN -extensions SAN \
#        -config <(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:*.ping-aws.com")
#
#    On Open SSL 1.1.1 or later, after creating the key, run this:
#      openssl req -sha256 -new -x509 -days 3650 \
#        -key ping-aws.rsa -out ping-aws.crt \
#        -subj /CN=ping-aws.com \
#        -addext "subjectAltName = DNS:*.ping-aws.com"
#
# ---
#
# To transform the RSA key (ping-aws.rsa) to PKCS#8 (ping-aws.key) format, run:
#   openssl pkcs8 -topk8 -inform PEM -outform PEM \
#     -in ping-aws.rsa -out ping-aws.key -nocrypt
#
# Copy the contents of ping-aws.crt and ping-aws.key into tls.crt and tls.key
# in the tls secret object below.

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-secret
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC2TCCAcGgAwIBAgIUFiQ25ymoV8OP6gfwkE9SMeqaRa8wDQYJKoZIhvcNAQEL
    BQAwFzEVMBMGA1UEAwwMcGluZy1hd3MuY29tMB4XDTE5MDkwMjE5MjE0M1oXDTI5
    MDgzMDE5MjE0M1owFzEVMBMGA1UEAwwMcGluZy1hd3MuY29tMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn299X54MUi+6cEw0b+JJTtdgQLLm13VebcbQ
    C2j3OZLk/IN+2juap8x1zijJZi1xaiJrNAE8jm/cHnoTn17gEyZc4G3HCyiUChk4
    8sGuQH6jywVrfrTacN2LtV7+utck9Sk66kb4xJVfJWyiL/BCx3kF9i31wYXH2g5/
    pI2YcgGd5flOiqC5aF3QmOYdxNrEA2/MTbtr2DYHGgWy5PCaitz5QlFlb41Vq25h
    9AERILllSwGyCewcWs20HS5eBEt+6rGq4Qe69+jUfun2vRRObhDQCUl2t8d77uuH
    AHuwLyVj/5DW/Mh+KybQvf+NJe7rSfHgZJ0rNTRDxvy2eBeb4wIDAQABox0wGzAZ
    BgNVHREEEjAQgg4qLnBpbmctYXdzLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAUJ7k
    9fmTQFwLtxQVdZR3VLR9ftewTq7jXbX2GQVrRtqkecmSqg86IkaA0RuVfclI9co9
    keC01XLT5gx6bSJXJVopwgJt1+dBMUpmFyfUn1Aya5ezM/UJPEbzChEi+LLH50nz
    ZL0Jfj2t+rnkdgIUo7XUiHJ6LElhi1p94EgWzylxlM6ZxWL0OJMobF/9VzTmW+gA
    eKo6W1EdqMtQ/tZezHspRb2hzHeck5ywVV5uEcsa0MJtPb090GMJO/ZTRb6Sfq0D
    N+d2nV+AjQncxhv8ZkMCHawyacBh3OpI3yWawSfPEHNGbrcWqm09xZBcnpxDGCzX
    Bu5cZ7pppmx6GOXtSg==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfb31fngxSL7pw
    TDRv4klO12BAsubXdV5txtALaPc5kuT8g37aO5qnzHXOKMlmLXFqIms0ATyOb9we
    ehOfXuATJlzgbccLKJQKGTjywa5AfqPLBWt+tNpw3Yu1Xv661yT1KTrqRvjElV8l
    bKIv8ELHeQX2LfXBhcfaDn+kjZhyAZ3l+U6KoLloXdCY5h3E2sQDb8xNu2vYNgca
    BbLk8JqK3PlCUWVvjVWrbmH0AREguWVLAbIJ7BxazbQdLl4ES37qsarhB7r36NR+
    6fa9FE5uENAJSXa3x3vu64cAe7AvJWP/kNb8yH4rJtC9/40l7utJ8eBknSs1NEPG
    /LZ4F5vjAgMBAAECggEAV4VURZD1Ioigx9SNVH3b0DPa2qlanxwG4iwpOJo+XJSO
    ry9gC1x84XATm0A4jqaTg7exMbMcEvTE2NYav3nNd7WvdmPMyAtWeNSvtlMr3Kuo
    LmKjR8LvxtVXRBEJtHc2Cn6/oKulFAULXffscHRrtCRzaViBd+KAeutKloJEFRCA
    VoRObKq5WAVKV+Ach6e5hoR481vzay6Gvp8i/QenZGFweoM4sAwFwbOGw9yAK6iv
    T5bq2wU6ksdHMIVjB5eHM8Q1efCwjtJ6P1/a9p1WOj/8VJ+ywyxqJnbybGRy+gUn
    KnvMTcNFS8QmA9lwV+LOe9FiDKSrS/a1KEflx4qoQQKBgQDKLDPg1brEgpdlkyTa
    lZNJkluZNxZG0rtzEl1zzChdhdN2Oswn5XEhstvTD86Kl3ck92VCqnDK/ROnKknV
    wJcVPh5i5iINI4na+4A7mH90U/TRfsmiU2bHd4rNxZT4v8F9Cw2ERb9grhOg2xyV
    28wiCc3Sm0NXuj5RG6NK4TfEXwKBgQDJ4mJIo+0Hm2GkBsMcE938BQvHNppk5kTh
    7RZjcYMnliND3pBRf1/ZBKHBGvAQLyM0e973EqE/jEedFsfuA6TSy2fHvLBvRTw9
    3om1EAdas+GnhiTr/w3IFelI48EXpwHAeaTOAeW96k6ptbDImaPoZjnQqUDV7HVm
    LlvhxgG2/QKBgH6Yu0uYykDvPXpfb35olzhEq5L/ibWDk9l0sIwoVUZq3IV2QAzj
    gboGU9yQU1c5jWPaftAGBmc1ni7ZLi7pUDH/Gev4C26KyHIVdrDax0TCpdThPcWl
    0AArfQFpLeWtva1dVHN1cWdK2gOp8PZuEh9mYDn2+25ds1P6qH/lE5SlAoGBALD4
    MuGsWPaHHaN0jgoJ3Fi0b6u00MjMFevaMfsAIVFNSiKPcgEO4A1UAxtMqs31FC5I
    u53oBdO3+3rX4nBhX1WtGo87d4pCrdkqP5qpr1iyQIfijnEVhpYzpujPRY+fRWjc
    +Tvg6+x7/XLFI2/lRopNOjcQdxZPjmYBE2gpc41dAoGACHLiVWE1BpaKIE5XvHOZ
    MZeZPQlfFDKYA6pmcoh8nT5Hz2N4YqoAbpca+nPqzoO3uSgV2f1cRdzJYqabu23D
    +50wgskdOQCnrOwCiveJfx8g/qHJ8uvqykPOwNAb4f/drj5QHG42TUkAWRLTeloD
    +Z0VvyetPa5Us2PVNojLJzw=
    -----END PRIVATE KEY-----
