# This defines the ingress for the Kibana dashboard
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  labels:
    app: kibana
spec:
  tls:
  - hosts:
    - logs-dev.ping-demo.com
    secretName: tls-secret
  rules:
  - host: logs-dev.ping-demo.com
    http:
      paths:
        # This rule gives external access to the dashboard
        # FIXME: The Kibana dashboard only works if base path is /
        - path: /
          backend:
            serviceName: kibana
            servicePort: 5601