apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"pingdirectory","company":"PingIdentity"},"name":"ds","namespace":"perf"},"spec":{"podManagementPolicy":"OrderedReady","replicas":3,"selector":{"matchLabels":{"app":"pingdirectory","company":"PingIdentity"}},"serviceName":"pingdirectory","template":{"metadata":{"labels":{"app":"pingdirectory","company":"PingIdentity"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"alpha.eksctl.io/nodegroup-name","operator":"In","values":["pd-perf"]}]}]}}},"containers":[{"env":[{"name":"K8S_STATEFUL_SET_NAME","value":"ds"},{"name":"K8S_STATEFUL_SET_SERVICE_NAME","value":"pingdirectory"}],"envFrom":[{"configMapRef":{"name":"pingdirectory-configmap-4b6t97f9d8"}}],"image":"pingidentity/pingdirectory:edge","imagePullPolicy":"Always","name":"ds","ports":[{"containerPort":636},{"containerPort":443},{"containerPort":389}],"readinessProbe":{"exec":{"command":["/bin/sh","-c","/opt/liveness.sh"]}},"resources":{"limits":{"cpu":"10","memory":"48Gi"},"requests":{"cpu":"10","memory":"48Gi"}},"volumeMounts":[{"mountPath":"/usr/local/secrets","name":"passwords","readOnly":true}]}],"terminationGracePeriodSeconds":300,"volumes":[{"name":"passwords","secret":{"defaultMode":256,"secretName":"passwords-h4g74k977t"}}]}},"updateStrategy":{"type":"RollingUpdate"}}}
  creationTimestamp: "2019-08-20T04:22:27Z"
  generation: 1
  labels:
    app: pingdirectory
    company: PingIdentity
  name: ds
  namespace: perf
  resourceVersion: "79429"
  selfLink: /apis/apps/v1/namespaces/perf/statefulsets/ds
  uid: 1de662d1-c302-11e9-956b-0a0c10e37fd8
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pingdirectory
      company: PingIdentity
  serviceName: pingdirectory
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pingdirectory
        company: PingIdentity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - pd-perf
      containers:
      - env:
        - name: K8S_STATEFUL_SET_NAME
          value: ds
        - name: K8S_STATEFUL_SET_SERVICE_NAME
          value: pingdirectory
        envFrom:
        - configMapRef:
            name: pingdirectory-configmap-4b6t97f9d8
        image: pingidentity/pingdirectory:edge
        imagePullPolicy: Always
        name: ds
        ports:
        - containerPort: 636
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 389
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "10"
            memory: 48Gi
          requests:
            cpu: "10"
            memory: 48Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/secrets
          name: passwords
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: passwords
        secret:
          defaultMode: 256
          secretName: passwords-h4g74k977t
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: ds-66f8c48b4b
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: ds-66f8c48b4b
  updatedReplicas: 3