apiVersion: v1
kind: Service
metadata:
  name: kube-metrics-adapter
  namespace: ping-cloud-samirgandhi
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: ping-cloud
    role: pingfederate