# This service exposes the pingfederate admin and OAuthPlayground ports to the
# cluster.

apiVersion: v1
kind: Service
metadata:
  name: pingfederate
spec:
  ports:
    - port: 9999
      name: pf-console
    - port: 9031
      name: oauthplayground