kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
#- ../common
- storage.yaml
- secret.yaml
- statefulset.yaml
- service.yaml

#namePrefix: pingdirectory-

commonLabels:
  role: pingdirectory

configMapGenerator:
- name: pingdirectory-environment-variables
  env: env_vars

vars:
- name: K8S_STATEFUL_SET_NAME
  objref:
    kind: StatefulSet
    name: ds
    apiVersion: apps/v1
- name: K8S_STATEFUL_SET_SERVICE_NAME
  objref:
    kind: Service
    name: pingdirectory
    apiVersion: v1