# Headless service that provides DNS between the pods in the pingdirectory
# topology

apiVersion: v1
kind: Service
metadata:
  name: pingdirectory
spec:
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  clusterIP: None