# This defines the ping data console deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole
spec:
  replicas: 1
  template:
    metadata:
      name: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
          name: http
        envFrom:
          - configMapRef:
              name: pingdataconsole-environment-variables